### PR TITLE
Bug 425

### PR DESCRIPTION
**Pull request by rminchev1**
@monitobeko  & @VladislavNikolov  pls. review

### CODE REVIEW

**Comment by rminchev1** [comment]
@VladislavNikolov  

Some tests failing:

net.hawkengine.http.tests.ArtifactControllerTests > zipFile_validData_statusOk FAILED
    java.lang.AssertionError at ArtifactControllerTests.java:72

net.hawkengine.http.tests.ArtifactControllerTests > zipFile_zipFilesErrorMessage_statusBadRequest FAILED
    java.lang.AssertionError at ArtifactControllerTests.java:114

**Comment by rminchev1** [comment]
aha just saw the fix :+1:

**Comment by rminchev1** [comment]
Any concerns for merging this?

**Comment by VladislavNikolov** [comment]
Everything looks good.

**Pull request merged**
