### PR TITLE
Bug 238

### PR DESCRIPTION
**Pull request by monitobeko**
Fixed updating and adding of Fetch Artifact tasks #238

### CODE REVIEW

**Comment by rminchev1** [comment]
@hpslavov  has this been tested?

**Comment by rminchev1** [comment]
@monitobeko  - the bug is still present. Once you go to the pipeline config screen and start editing various parts of it e.g. stage name, pipeline name etc. going back and forth ugly  things happened.  Please test the entire pipeline config screen.

**Comment by rminchev1** [comment]
also make sure you merge the current master to the branch b/c bunch of things changed.

**Comment by VladislavNikolov** [comment]
Bug will be fixed with pull request #304

**Pull request closed without merging**
